### ISSUE TITLE
Issue with Input Element Width Expansion on Click

### ISSUE THREAD

**Issue by Heet-Bhalodiya** [guilhermerodz/input-otp#55]
## Expected Behavior
The library should provide properties that allow direct modification of the input styles.

## Current Behavior
Screenshots of the issue are attached for reference:

![CPT2406201907-485x312](https://github.com/guilhermerodz/input-otp/assets/100203834/417cd029-9bda-4b63-bb4f-5ddcc42616b1)

![image](https://github.com/guilhermerodz/input-otp/assets/100203834/4ae64083-7316-44e8-8e4c-f7a217b7e802)

When clicking on the slot, an additional 40px width is added to the input element. To address this issue, I have to add the following styles in the global.css file:

```css
input[autocomplete='one-time-code'][data-input-otp='true'] {
  inline-size: 100% !important;
}
```

I appreciate your assistance in resolving this matter.
